"""Make Item.guid not null

Revision ID: 29b2615a5fbb
Revises: 227fb7b1409b
Create Date: 2012-11-23 10:20:08.996076

"""

# revision identifiers, used by Alembic.
revision = '29b2615a5fbb'
down_revision = '227fb7b1409b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    items = table('items',
            column('guid', sa.TEXT())
            )
    op.execute(items.update()\
            .where(items.c.guid==None)\
            .values({'guid':op.inline_literal('noguid')})
            )
    op.alter_column('items', u'guid',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', u'guid',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
