"""Add itemtopics table

Revision ID: 323be16ffddd
Revises: 6a172eccde1
Create Date: 2012-11-29 21:19:35.766645

"""

# revision identifiers, used by Alembic.
revision = '323be16ffddd'
down_revision = '6a172eccde1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemtopics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('topic', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemtopics')
    ### end Alembic commands ###
