"""Add itemtopicnames table

Revision ID: 39a6f2aebff4
Revises: 323be16ffddd
Create Date: 2012-11-30 01:44:30.418334

"""

# revision identifiers, used by Alembic.
revision = '39a6f2aebff4'
down_revision = '323be16ffddd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemtopicnames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('topicname', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['item'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemtopicnames')
    ### end Alembic commands ###
