"""Add etag column

Revision ID: 6a172eccde1
Revises: 12b94e1a376
Create Date: 2012-11-29 08:14:39.913775

"""

# revision identifiers, used by Alembic.
revision = '6a172eccde1'
down_revision = '12b94e1a376'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('etag', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'etag')
    ### end Alembic commands ###
