"""Add itemscores table

Revision ID: cd7de59a304
Revises: 39a6f2aebff4
Create Date: 2012-11-30 02:50:36.177671

"""

# revision identifiers, used by Alembic.
revision = 'cd7de59a304'
down_revision = '39a6f2aebff4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemscores')
    ### end Alembic commands ###
